# Permalinks
permalink:        pretty

# Setup
baseurl:          ""
url:              https://paseli.ch

title:            Elisabetta & Pascal heiraten!
partner1:         Elisabetta
partner2:         Pascal
wedding-year:     2026
wedding-month:    7
wedding-day:      25
wedding-hour:     16
wedding-tag:      Juli 25, 2026 Montreux
wedding-location: Fairmont Montreux Palace, Montreux, VD
copyright:        Elisabetta & Pascal
#rsvp-link:        https://www.zola.com/wedding/elisabettaandpascal/rsvp
