# Permalinks
permalink:        pretty

# Setup
baseurl:          ""
url:              https://paseli.ch

title:            Elisabetta & Pascal are getting married!
partner1:         Elisabetta
partner2:         Pascal
wedding-year:     2026
wedding-month:    7
wedding-day:      25
wedding-hour:     16
wedding-tag:      July 25th, 2026 Montreux
wedding-location: Fairmont Montreux Palace, Montreux, VD
copyright:        Pascal Baur & Elisabetta
rsvp-link:        https://www.zola.com/wedding/elisabettaandpascal/rsvp
